### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by blainesch** [Rush/node-authenticate-pam#11]
~~~ bash
-> % npm --version
1.4.28

-> % node --version
v0.10.33

-> % npm install authenticate-pam
/
> authenticate-pam@0.2.2 preinstall /Users/bschmeisser/sites/devup/apps/web-terminal/node_modules/authenticate-pam
> node-gyp configure && node-gyp build


module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /Users/bschmeisser/sites/devup/apps/web-terminal/node_modules/authenticate-pam
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing authenticate-pam@0.2.2

> authenticate-pam@0.2.2 preuninstall /Users/bschmeisser/sites/devup/apps/web-terminal/node_modules/authenticate-pam
> rm -rf build/*
~~~

**Comment by cthayer** [comment]
For anyone else who ends up here, the solution is to install the `nan` module before the `authentication-pam` module.  Steps detailed below:

```
npm install nan
npm install authentication-pam
```
