### ISSUE TITLE
depreciated option --no-parrallel

### ISSUE THREAD

**Issue by Thetoxicarcade** [Rush/node-authenticate-pam#13]
Random depreciated option (also available in full color!):
```
@cant sudo npm install -G authenticate-pam

> authenticate-pam@0.2.2 preinstall /home/cant/node_modules/authenticate-pam
> node-gyp configure && node-gyp build

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /home/cant/node_modules/authenticate-pam
gyp ERR! node -v v0.10.34
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! authenticate-pam@0.2.2 preinstall: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the authenticate-pam@0.2.2 preinstall script.
npm ERR! This is most likely a problem with the authenticate-pam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls authenticate-pam
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-G" "authenticate-pam"
npm ERR! cwd /home/cant
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

> authenticate-pam@0.2.2 preuninstall /home/cant/node_modules/authenticate-pam
> rm -rf build/*

npm ERR! not ok code 0
```
![screenshot from 2015-03-15 06 29 54](https://cloud.githubusercontent.com/assets/4575799/6655966/ca272f7e-cadc-11e4-81b6-a3fd0bbc5ddb.png)

**Comment by Thetoxicarcade** [comment]
I get this strange feeling it has little to nothing to do with your code. c:

**Comment by Rush** [comment]
Sorry, no idea.
