### ISSUE TITLE
Configure error: spawn ENOENT

### ISSUE THREAD

**Issue by srossross** [Rush/node-authenticate-pam#14]
I'm not sure how to debug this error. Have you seen this before?

```
+ npm install authenticate-pam
npm WARN package.json wnext@0.0.0 No repository field.
-
> authenticate-pam@0.2.2 preinstall /Users/sean/Documents/workspace/wnext/node_modules/authenticate-pam
> node-gyp configure && node-gyp build

gyp ERR! configure error 
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/sean/anaconda/envs/_build/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /Users/sean/Documents/workspace/wnext/node_modules/authenticate-pam
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! authenticate-pam@0.2.2 preinstall: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the authenticate-pam@0.2.2 preinstall script.
npm ERR! This is most likely a problem with the authenticate-pam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls authenticate-pam
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/sean/anaconda/envs/_build/bin/node" "/Users/sean/anaconda/envs/_build/bin/npm" "install" "authenticate-pam"
npm ERR! cwd /Users/sean/Documents/workspace/wnext
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

```

**Comment by Rush** [comment]
Are you compiling on Mac? Does Mac even have libpam?

**Comment by srossross** [comment]
Yes, I have `libpam` installed I also just filed an issue with npm.
npm/npm#7659
