### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by rezen** [Rush/node-authenticate-pam#16]
I wasn't having luck installing via npm so I cloned and manually built. node-gyp builds without errors, but when I run the test script an error is throw. I'm on CentOS release 6.7

```````````
$ node --version
v0.12.7
$ npm --version
2.11.3
$node-gyp --version
v2.0.2
$ node test.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/node-authenticate-pam/test.js:2:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```````````````````

**Comment by rezen** [comment]
Turns out it was a building issue. `node-gyp rebuild -target=v0.12.7` addressed the problem.

**Comment by Rush** [comment]
@rezen glad that it works, can we close this issue? This is a common problem with all binary addons I believe.

**Comment by rezen** [comment]
Yes, thank you!

**Comment by Ajaay** [comment]
I'm having the same issue but the node-gyp rebuild has not worked for me. I was working fine on v0.10 but it broke when I upgraded to 0.12.

I've now downgraded back to 0.10 and I'm getting the same issue. 

Any ideas?

Thanks
